import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from 'next/script'; // Pastikan Script diimpor
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Script Monetag yang baru ditambahkan */}
        {/* Anda bisa memilih strategy yang berbeda jika diperlukan (misalnya, 'beforeInteractive', 'lazyOnload') */}
        {/* Atribut 'data-zone' dan 'data-sdk' akan diteruskan sebagai atribut HTML standar */}
        <Script 
          id="monetag-libtl-sdk" // ID unik untuk skrip ini
          src="//libtl.com/sdk.js" 
          data-zone="9375207" 
          data-sdk="show_9375207" 
          strategy="afterInteractive" // Atau strategy lain yang sesuai
          onLoad={() => {
            console.log('Monetag libtl SDK loaded successfully via layout.tsx');
            // Anda bisa menambahkan logika inisialisasi di sini jika SDK memerlukannya
            // dan jika window.show_9375207 sudah tersedia
            if (typeof window.show_9375207 === 'function') {
              // Contoh: Panggil fungsi inisialisasi jika ada
              // window.show_9375207({ option: 'value' }); 
            }
          }}
          onError={(e) => {
            console.error('Failed to load Monetag libtl SDK via layout.tsx:', e);
          }}
        />
        {/* Skrip lain yang mungkin sudah ada di head Anda */}
      </head>
      <body className={inter.className}>
        {children}
        {/* Skrip lain yang mungkin ada di akhir body Anda */}
      </body>
    </html>
  );
}

{/* Skrip untuk Iklan Rewarded Interstitial */}
<Script 
  src="YOUR_MONETAG_REWARDED_INTERSTITIAL_SCRIPT_URL.JS" // GANTI DENGAN URL SKRIP IKLAN REWARDED ANDA
  strategy="lazyOnload" // atau afterInteractive, sesuaikan dengan kebutuhan
  onLoad={() => {
    console.log('Skrip iklan rewarded interstitial berhasil dimuat.');
    // Anda bisa melakukan inisialisasi iklan di sini jika diperlukan oleh platform
    // Misalnya, jika ada fungsi init khusus untuk rewarded ads:
    // if (typeof window !== 'undefined' && (window as any).MyRewardedAdPlatform) {
    //   (window as any).MyRewardedAdPlatform.init({ /* opsi */ });
    // }
  }}
  onError={(e) => {
    console.error('Error memuat skrip iklan rewarded interstitial:', e);
  }}
/>
